"use client";

import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";

import Hero from "./components/hero";

import { source_sans_pro } from "./fonts";
import { lora } from "./fonts";

export const metadata = {
  title: "Portfolio 2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={source_sans_pro.className}>
      <head></head>
      {/* add global styling here */}

      <body
        className="
      min-h-screen
      bg-green-600
      bg-opacity-40
      text-gray-900
      "
      >
        <div
          className="
        mx-24 
        lg:mx-24
        "
        >
          <header>{/* <NavBar></NavBar> */}</header>
          <Hero></Hero>
          {children}
        </div>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
