"use client";

import React, { useState, useEffect } from "react";
import "./globals.css";

import { PageWrapper } from "./page-wrapper";
import { source_sans_pro } from "./fonts";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata = {
  title: "Portfolio 2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={source_sans_pro.className}>
      <head></head>

      <body className="">
        <div className="">
          <header>
            <Navbar />
          </header>
          <PageWrapper>{children}</PageWrapper>
        </div>

        <footer className="">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
